proposed/spec-draft-1.yaml, proposed/spec.yaml
Cleaned up 'building' examples and updated descriptions
Got rid of 'file size' as it migrated out of the core imagery metadata
Changed name to reflect this is just one proposal
=> Proposed cleanup

README.md, api-spec/README.md
Updates for the main readme, as well as a new readme for the STAC API.
=> Readme updates

static-catalog/README.md
Please review. I updated the narrative for static STAC catalogs. I'll do another pass as schema changes solidify.
=> Static readme file updates

api-spec/README.md, api-spec/STAC-standalone.yaml, api-spec/wfs-stac.md
Pushing ahead with some narrative updates. I'll likely continue to add to this branch - just want to be sure there are some eyes on it. Feel free to commit whenever makes sense @hgs-msmith and then I can just start a new PR.
=> Stac api updates [WIP]

api-spec/STAC-fragment.yaml, api-spec/STAC-standalone.yaml, api-spec/WFS3core+STAC.yaml
@hgs-msmith and @hgs-trutherford - I wanted you guys to take a look at these. I updated for the latest json spec. Was hoping to just make narrative changes today, but things also need to be in line with the specs.
I'd like to do more to make things consistent, like update all the examples to be consistent how an api might actually be designed. And maybe its a separate doc, but I'd like an example openapi thing that is not templated, that shows 'real' STAC collections in the WFS.
But not sure if I'll get to that today, so submitting this for review. If you don't manage to review by the end of the day that's cool, I'll merge in, just wanted to be sure this was seen.
=> Stac api updates for latest json spec

api-spec/README.md, api-spec/STAC-standalone-swagger2.yaml, api-spec/WFS3core+STAC-swagger2.yaml
Here is a swagger 2 version of the api that generates working code with the Swagger Tools. I believe there may be one or two bugs in the OpenAPI 3 version that this backport has exposed. I am working on those next.
=> Swagger2 version of 0.4.0 api

api-spec/STAC-fragment.yaml, api-spec/STAC-standalone.yaml, api-spec/WFS3core+STAC.yaml
=> removed start and end in ItemProperties in favor of date time 

json-spec/json-schema/stac-item.json
Redoing https://github.com/radiantearth/stac-spec/pull/120 to be against dev
=> Object validation

api-spec/sorting-fragment.yaml
=> Adding sorting fragment extensions.

extensions/stac-eo-spec.md
[issue #141](https://github.com/radiantearth/stac-spec/issues/141)
=> added constellation to eo extension

README.md, api-spec/README.md, extensions/README.md, extensions/examples/README.md, extensions/stac-eo-spec.md, how-to-help.md, json-spec/README.md, json-spec/json-spec.md, roadmap.md, static-catalog/static-recommendations.md
As discussed on Gitter, profiles and extensions are used synonymous anyway.
=> Profiles => Extensions

extensions/stac-collection-spec.md, static-catalog/README.md
=> Allows CommonMark (Markdown) in descriptions

json-spec/json-spec.md
This adds some examples and explanations for using mime types. I included a list of what seemed like some common types for geospatial data and took a stab at how to approach mime types for assets where it might not be immediate clear (as can be the case for some sidecar files).
=> Add examples and suggestions for mime types

catalog-spec/catalog-spec.md, dataset-spec/dataset-spec.md, item-spec/item-spec.md
See #179 
We likely should also create an extension that more fully spells out some of the ideas for this field, as well as additions to make the links more useful. Like explain that it could be used to link to non-STAC metadata, etc. But wanted to get this in so people could start to use it.
=> Added the derived_from relation

extensions/README.md, extensions/scientific/README.md, extensions/stac-collection-spec.md, extensions/stac-eo-spec.md, extensions/stac-start-end-datetime-spec.md, extensions/transaction/README.md
Added a classification system for extension maturity, for #220
=> Extension maturity

README.md
update readme to reflect new version on master
=> update readme to reflect new version

collection-spec/collection-spec.md
Missed to add it to collections, sorry.
=> Added missing title property for links in collections.

implementations.md
Updated information for 0.6.0 implementation
=> Update Implementations.md for 0.6.0

implementations.md
Added in DevSeed implementations: Landsat catalog, sat-api, sat-stac, sat-search.
Also added in stac-validator for @jbants
=> add DevSeed implementations (and SparkGeo's stac validator)

implementations.md
* Updated planet catalog info to 0.6.0
* added versions to a couple implementations
* moved implementations not up to 0.6.0 to 'outdated' section
=> Update for Planet catalog, other tweaks

extensions/README.md, extensions/checksum/README.md, extensions/checksum/example-sentinel1.json, extensions/checksum/schema.json
This is a simple extension that allows adding checksums to links and assets. Have seen that in some examples and wanted to use it in my implementation so just made a spec, example and JSON schema for it.
=> Checksum extension

collection-spec/collection-spec.md
Another one of these 'facepalm' situations where you don't know why the hell you've done what you've done.
=> Replaced temporal with spatial in collection description

extensions/sar/README.md, extensions/sar/schema.json
Changed the units field in the SAR extention to SI (+ UDUNITS) as discussed yesterday.
=> SAR: Changed the units to SI/UDUNITS.

extensions/eo/example-landsat8.json
=> [STAC-417] Added href to the asset called index

extensions/README.md
The summary of the scientific extension was outdated and still referred explicitly to collections.
=> Updated outdated summary of the scientific extension.

api-spec/STAC+extensions.yaml, api-spec/STAC.yaml, api-spec/api-spec.md, api-spec/openapi/STAC.merge.yaml, api-spec/openapi/STAC.yaml
For more information and discussions see #430.
=> Added search link to /stac and made POST /stac/search not mandatory

api-spec/STAC-extensions.yaml, api-spec/STAC.yaml, api-spec/extensions/transaction/transaction.fragment.yaml, api-spec/openapi/STAC.yaml
Updates all references to geojson.org
=> update all geojson schema refs

CHANGELOG.md
=> Updated changelog for 0.7.0

api-spec/extensions/search/README.md, api-spec/extensions/search/examples/example.json, api-spec/extensions/search/schema.json
https://github.com/opengeospatial/WFS_FES/blob/980a445f6bc89cb7a2804feb59ca1505a901ebe1/core/openapi/schemas/featureCollectionGeoJSON.yaml
=> rename search extension found to matched per WFS3 terms

api-spec/extensions/search/README.md, catalog-spec/catalog-spec.md, collection-spec/collection-spec.md, extensions/checksum/README.md, extensions/eo/README.md, extensions/label/README.md, extensions/pointcloud/README.md, extensions/sar/README.md, extensions/scientific/README.md, item-spec/item-spec.md
**Related Issue(s):** #541
1. Added several links to improve the user experience.
=> Added links to chapters to improve navigation / UI (#541).

catalog-spec/json-schema/catalog.json, collection-spec/json-schema/collection.json, item-spec/json-schema/item.json
**Related Issue(s):** None, reported by @a-kirk on Gitter.
1. Fixes the JSON schemas for stac_extensions
=> Fixed JSON schema for stac_extensions (thanks @a-kirk).

api-spec/STAC-extensions.yaml, api-spec/STAC.yaml, api-spec/api-spec.md, api-spec/openapi/STAC.yaml, api-spec/openapi/WFS3.yaml, api-spec/package-lock.json
N/A
1. Updates the open api schemas to update the `next` field definition and match the definitions in the markdown with the ones given in the yaml file
=> Fix yaml definitions

extensions/asset/examples/example-landsat8.json, extensions/checksum/examples/example-sentinel1.json, extensions/label/examples/multidataset/catalog.json, extensions/label/examples/multidataset/spacenet-buildings/catalog.json, extensions/label/examples/multidataset/zanzibar/catalog.json, extensions/label/examples/spacenet-roads/roads_collection.json
#581 
1. Updated STAC extension examples with correct extension scope
=> Update `stac_extension` in the extension examples

extensions/label/README.md
=> Label Extension: Clarify label:assets purpose

extensions/label/examples/multidataset/spacenet-buildings/AOI_2_Vegas_img2636.json, extensions/label/examples/multidataset/spacenet-buildings/AOI_3_Paris_img1648.json, extensions/label/examples/multidataset/spacenet-buildings/AOI_4_Shanghai_img3344.json, extensions/label/examples/multidataset/zanzibar/znz001.json, extensions/label/examples/multidataset/zanzibar/znz029.json, extensions/label/examples/spacenet-roads/roads_item.json
When doing #597, I found several issues in the label extension examples. I ran them all though a JSON Schema Validator and fixed them according to the Schema. Afterwards, all were also passed through a JSON Formatter.
=> Fix label extension examples

CHANGELOG.md, README.md, api-spec/README.md, api-spec/STAC-extensions.yaml, api-spec/STAC.yaml, api-spec/api-spec.md, api-spec/examples.md, api-spec/extensions/transaction/transaction.fragment.yaml, api-spec/openapi/STAC.yaml, api-spec/openapi/WFS3.yaml, best-practices.md, collection-spec/README.md, collection-spec/collection-spec.md
**Related Issue(s):** #512, #604
1. Update OAFeat 1.0.0-draft2 to 1.0.0 final
2. Replace WFS with OAFeat (abbrev. to be confirmed by OGC).
As far as I can see there are no breaking changes, but I'm not 100% sure. Please review carefully.
=> Align with OGC API - Features 1.0.0 final

api-spec/api-spec.md
1. The single(!) collectionId is not an array
=> collectionId is not an array

api-spec/examples.md
1. Fixed issue with pagination examples
2. Added GET based example as well
=> fixing examples to include method

collection-spec/examples/landsat-collection.json, collection-spec/examples/landsat-item.json, item-spec/examples/digitalglobe-sample.json, item-spec/examples/sentinel2-sample.json
1. Several stac_extensions were not correctly used.
=> Fixed stac_extensions in examples

catalog-spec/catalog-spec.md
**Related Issue(s):** #678
1. see #678
=> Clean-up catalog relations and links

extensions/eo/json-schema/schema.json, extensions/sar/json-schema/schema.json, item-spec/json-schema/item.json
**Related Issue(s):** N/A
1. Validate the eo:bands/sar:polarizations correctly in the assets
=> Validate SAR and EO asset extensions correctly.

CHANGELOG.md, api-spec/STAC-extensions.yaml, api-spec/STAC.yaml, api-spec/extensions/fields/README.md, api-spec/openapi/OAFeat.yaml, api-spec/openapi/STAC.yaml
resolves #587
1. update yaml schema to clarify how bbox filter is passed to get requests
=> update schema for bbox which fixes #587

CHANGELOG.md, api-spec/STAC-extensions.yaml, api-spec/extensions/query/query.fragment.yaml
**Related Issue(s):** #692 
1. Update YAML types to reflect what's being done in practice
2. Update examples to be correct wrt spec
These are technically breaking changes, but I think they more accurately reflect the handful of implementations of this.
=> Query polish

CHANGELOG.md
1. Change date in changelog for #706
=> Change date in CHANGELOG

CHANGELOG.md, item-spec/common-metadata.md, item-spec/item-spec.md, item-spec/json-schema/basics.json, item-spec/json-schema/item.json
N/A
1. Corrects item jsonschema to evaluate all common metadata schemas 
2. Item-spec and common-metadata documentation updated with more information about common metadata fields.
=> Common metadata updates

CHANGELOG.md
**Related Issue(s):** #746 
Updated the changelog to reflect the changes done in #746 
=> Proj changelog update

implementations.md
none
1. Add pygeoapi to implementations page.
=> add pygeoapi

CHANGELOG.md, CODE_OF_CONDUCT.md
1. Added a code of conduct, requested by netlify, but also a good thing to have.
2. 
=> added code of conduct

CHANGELOG.md, best-practices.md, item-spec/examples/sample-full.json, item-spec/item-spec.md
**Related Issue(s):** #681 #766 
1. Move the two best practices in item spec to the 'best practices' document
2. Add rel 'alternate' with type html recommendation to communicate that there is an html version. (can make an issue of this to discuss), and updated example
3. Removed 'warning' on item spec, as it has been stable and we are moving to 1.0-beta
=> Item spec tweaks

.circleci/rc.yaml, CHANGELOG.md, extensions/datacube/README.md, extensions/projection/README.md, extensions/sat/README.md, extensions/sat/json-schema/schema.json, extensions/scientific/README.md, extensions/scientific/json-schema/schema.json, extensions/view/README.md, extensions/view/json-schema/schema.json
**Related Issue(s):** #795
1. Require at least one field for each extension
=> Require at least one extension field. #795

item-spec/common-metadata.md
**Related Issue(s):** #837
1. Solves #837
=> Clarification for common metadata

README.md
**Related Issue(s):** #850 
1. clarify we use sem ver
=> added sem ver clarification - #850

extensions/scientific/json-schema/schema.json
**Related Issue(s):** #847
1. Forgot to update this schema in #847, d'oh!
=> Fix schema

extensions/pointcloud/json-schema/schema.json
1. Makes the JSON schema for point cloud into valid json
2. 
=> Valid JSON schema in pointcloud extension

extensions/scientific/README.md
The old link was broken and now it's an offical RFC.
1. https://tools.ietf.org/id/draft-vandesompel-citeas-03.html is an old draft
2. https://tools.ietf.org/id/draft-vandesompel-citeas-04.html is the most recent draft
3. https://tools.ietf.org/html/rfc8574 is the live RFC
=> scientific/README.md: draft-vandesompel-citeas -> RFC 8574

CHANGELOG.md, extensions/scientific/README.md, extensions/scientific/json-schema/schema.json
**Related Issue(s):** #910 @schwehr
1. Relaxed the regular expression for DOIs in the scientific extension
=> Relaxed the regular expression for DOIs in the scientific extension #910

CHANGELOG.md, extensions/file/README.md, extensions/file/json-schema/schema.json
**Related Issue(s):** #922, #933 
After a discussion with Matt, we propose to add some new fields to the file extension as they seem pretty related to the file (content).
=> Additional File Fields

extensions/eo/README.md, extensions/eo/json-schema/schema.json, item-spec/examples/sample-full.json
**Related Issue(s):** #960 #822 
1. Updated eo bands descriptions for more clarity
2. Put in h4's for better linking
=> EO Clarifications

extensions/projection/README.md
**Related Issue(s):** #976 #822 
1. Added best practices section
2. More tools
3. Added h4's instead of bold, for linking.
=> Proj recommendations and formatting

extensions/README.md
1. Add CARD4L Extensions to vendor list
=> Add CARD4L Extensions to vendor list

best-practices.md
**Related Issue(s):** #1006 
1. Did a bit of reorganizing of the best practice document, and put more groupings, so it's a bit more broken up.
=> Best practice headings and reorg

item-spec/common-metadata.md
**Related Issue(s):** #1015
1. Add the unit for the field gsd to the table for better visibility.
=> Add gsd unit to table

catalog-spec/catalog-spec.md, collection-spec/collection-spec.md, item-spec/item-spec.md
=> Fix formatting of media types for spec

catalog-spec/json-schema/catalog-core.json, catalog-spec/json-schema/catalog.json
1. Some potential improvements for the JSON Schema for catalogs (@lossyrob )
=> Catalog Core improvements

CHANGELOG.md, catalog-spec/json-schema/catalog-core.json, catalog-spec/json-schema/catalog.json, collection-spec/json-schema/collection.json, examples/catalog.json, examples/collection-only/collection.json, examples/collection.json, examples/collectionless-item.json, examples/core-item.json, examples/extended-item.json, examples/extensions-collection/collection.json, examples/extensions-collection/proj-example/proj-example.json, examples/simple-item.json, extensions/eo/json-schema/schema.json, extensions/projection/json-schema/schema.json, extensions/scientific/examples/collection.json, extensions/scientific/examples/item.json, extensions/scientific/json-schema/schema.json, extensions/view/README.md, extensions/view/json-schema/schema.json, item-spec/json-schema/basics.json, item-spec/json-schema/datetime.json, item-spec/json-schema/instrument.json, item-spec/json-schema/item.json, item-spec/json-schema/licensing.json, item-spec/json-schema/provider.json, package.json
=> Update version numbers

CHANGELOG.md
**Related Issue(s):** #968
1. Updated changelog language to be a bit more consistent
2. removed non-core extension changes
3. add links to relevant PR's
4. organized things so more important ones are more near the top of each section.
=> changelog organization, clarification, links

CHANGELOG.md
=> Remove additional line in changelog

.circleci/config.yml
#1038 
Update regex to match version tags when cutting a release
=> update tag regex for publishing schemas

extensions/README.md
**Related Issue(s):** #1041, #1040
1. Most Extensions now also support Collection (Assets)
2. Changes as proposed in #1041
=> Update Extensions README

examples/extended-item.json
**Related Issue(s):** #982
1. Linked to the remote data schema that @matthewhanson made. The stac validator does not seem to be working yet with rc.1 (though I may be doing something wrong). But I put it at beta.2 and verified it worked (and failed if I changed fields), so I think it should be good.
=> linked to remote data schema for proper example

best-practices.md
**Related Issue(s):** #1017
1. Added visual and overview role recommendations
=> Added visual and overview role recommendations

CHANGELOG.md, catalog-spec/json-schema/catalog-core.json, catalog-spec/json-schema/catalog.json, collection-spec/json-schema/collection.json, examples/catalog.json, examples/collection-only/collection.json, examples/collection.json, examples/collectionless-item.json, examples/core-item.json, examples/extended-item.json, examples/extensions-collection/collection.json, examples/extensions-collection/proj-example/proj-example.json, examples/simple-item.json, item-spec/json-schema/basics.json, item-spec/json-schema/datetime.json, item-spec/json-schema/instrument.json, item-spec/json-schema/item.json, item-spec/json-schema/licensing.json, item-spec/json-schema/provider.json
=> update version to 1.0.0-rc.2

.circleci/config.yml, collection-spec/collection-spec.md
**Related Issue(s):** #1038
1. Just fixing a typo
2. I've also added another attempt to fix the schema publishing #1038
=> Fix typo and CI

CHANGELOG.md, examples/catalog.json, examples/collectionless-item.json
**Related Issue(s):** #1081
1. Fixes collectionless item
=> Collectionless item has collection field & link #1081

.circleci/rc.yaml, .github/pull_request_template.md, .remarkignore, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, best-practices.md, catalog-spec/README.md, collection-spec/README.md, collection-spec/collection-spec.md, examples/README.md, extensions/README.md, item-spec/common-metadata.md, item-spec/item-spec.md, overview.md, principles.md, process.md
1. Not many PRs open so took the chance to finally fully adopt the markdown style check fully for the stac spec. It's already in place for API spec and extensions, so the core spec should follow.
=> Fix Markdown

overview.md
=> Minor change to Collection usage wording

best-practices.md, catalog-spec/catalog-spec.md, collection-spec/collection-spec.md, item-spec/item-spec.md, overview.md
**Related Issue(s):** #1082 
1. Various little tweaks to make it clear that the 'root' can be a Catalog or Collection
2. Or small language tightening that came up as reading.
=> updates to make clear root can be catalog or collection

CHANGELOG.md, collection-spec/collection-spec.md, collection-spec/json-schema/collection.json, item-spec/common-metadata.md, item-spec/item-spec.md, item-spec/json-schema/datetime.json
**Related Issue(s):** #1095
1. JSON Schema to check all timestamps end with `Z` or `+00:00`
2. Add UTC restriction to created and updated
3. Add UTC restriction to temp. extents in collections
=> All timestamps in UTC

CHANGELOG.md, best-practices.md
**Related Issue(s):** #1090, https://github.com/opengeospatial/ogcapi-records/issues/94
1. Add a new relation type to best practices for a preview, see PR for more details.
=> Add preview relation type #1090

item-spec/common-metadata.md
=> minor editorial cleanup for common-metadata

CHANGELOG.md, best-practices.md, examples/core-item.json, examples/extended-item.json, examples/simple-item.json
**Related Issue(s):** #1098 
1. Added line in best practices about having root and parent point at the same place
2. updated examples to follow this best practice.
=> Best practice when root == parent clarification

catalog-spec/json-schema/catalog.json
**Related Issue(s):** #1100
1. Catalog: Require child / item in links (add to json schema)
=> Catalog: Require child / item in JSON Schema #1100

CHANGELOG.md, catalog-spec/json-schema/catalog-core.json, catalog-spec/json-schema/catalog.json, collection-spec/json-schema/collection.json, examples/catalog.json, examples/collection-only/collection-with-schemas.json, examples/collection-only/collection.json, examples/collection.json, examples/collectionless-item.json, examples/core-item.json, examples/extended-item.json, examples/extensions-collection/collection.json, examples/extensions-collection/proj-example/proj-example.json, examples/simple-item.json, item-spec/json-schema/basics.json, item-spec/json-schema/datetime.json, item-spec/json-schema/instrument.json, item-spec/json-schema/item.json, item-spec/json-schema/licensing.json, item-spec/json-schema/provider.json, package.json
1. Changed versions to rc.3
2. Updated changelog, put issue/pr links for all lines on it.
=> Version changes for rc3

CHANGELOG.md, catalog-spec/catalog-spec.md, catalog-spec/json-schema/catalog.json
**Related Issue(s):** #1115
1. Remove the requirement that disallows empty catalogs. 
*Note: Said this is not a breaking change, as this is just relaxing a requirement, but could mark it as breaking if that is desired. It is a fairly major change, does require a new RC to be cut*
=> Allow empty catalogs

CHANGELOG.md
1. Removed shortcut changelog from rc.3
2. periods
=> minor changelog fixes

.circleci/config.yml
**Related Issue(s):** #1130 
1. Added python stac-validator to circle ci
=> CI Validation 

best-practices.md, examples/catalog.json, examples/collection-only/collection-with-schemas.json, examples/collection-only/collection.json, examples/collection.json, examples/collectionless-item.json, examples/core-item.json, examples/extended-item.json, examples/extensions-collection/collection.json, examples/extensions-collection/proj-example/proj-example.json, examples/simple-item.json
**Related Issue(s):** #1132 
1. Added small best practice section on links
2. updated examples
=> added best practice to include title, updated examples

.circleci/config.yml
**Related Issue(s):** #1136 
1. comment out python validator from circleci
=> Comment out python ci validation

examples/catalog.json
**Related Issue(s):**
N/A
1. Minor change to catalog example - fixed the collectionless item title
=> docs: fix collectionless item title in catalog example

collection-spec/collection-spec.md
**Related Issue(s):** N/A
1. Fix a typo
**or**~ a CHANGELOG entry is not required.
and I have opened issue/PR #XXX to track the change.~
=> Fix a typo in collection-spec.md

best-practices.md
1. Fix punctuation in best practices document.
**or**~ a CHANGELOG entry is not required.
- ~[ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec),
and I have opened issue/PR #XXX to track the change.~
=> Minor punctuation fix in best practices

overview.md, principles.md, process.md
No associated ticket.  Minor spelling changes only.
A few spelling changes.
=> Minor spelling changes

.remarkignore, CODE_OF_CONDUCT.md
**Related Issue(s):** 
n/a
1. update code of conduct to version 2.1 
=> update code of conduct to v2.1

CHANGELOG.md, best-practices.md, catalog-spec/catalog-spec.md, collection-spec/collection-spec.md, item-spec/item-spec.md
**Related Issue(s):** #1212 
1. Clarify that trailing slashes are significant.
=> Clarified that trailing slashes in URIs are significant.

CHANGELOG.md, collection-spec/collection-spec.md
**Related Issue(s):** #1201
1. As discussed in the PSC meeting, this clarifies the wording regarding the uniqueness of collection IDs. This superceedes PR #1201.
=> Clarify wording regarding uniqueness of collection IDs

examples/collection-only/collection-with-schemas.json, examples/extensions-collection/collection.json
#1152 
1. Spelling change in  schema example files.
=> Spelling corrections

examples/core-item.json, examples/extended-item.json
=> Fix media type in example

best-practices.md
**Related Issue(s):** #1214, #1212
This fine-tunes PR #1214 after some discussions in https://github.com/radiantearth/stac-api-spec/pull/404#discussion_r1133889095
=> Fine-tune best practice for URLs

CHANGELOG.md, best-practices.md
**Related Issue(s):** #1195
1. Do not recommend subdirectories for Items without sidecar files #1195
=> Best practice: Do not recommend subdirectories for Items without sidecar files #1195

CHANGELOG.md, best-practices.md
Closes #1231
1. Reworded the description around URL resolving
2. More examples that show how URL resolving works - all examples were tested with [URI.js](https://medialize.github.io/URI.js/)
=> Improve URL resolving #1231

item-spec/item-spec.md
**Related Issue(s):** #1228
1. Clarify the inheritance of the asset properties 
2. 
=> Clarify the inheritance of the properties at different levels

commons/common-metadata.md
=> Fix small grammer error in common metadata

CHANGELOG.md, CITATION.cff, README.md, catalog-spec/json-schema/catalog.json, collection-spec/json-schema/collection.json, examples/catalog.json, examples/collection-only/collection-with-schemas.json, examples/collection-only/collection.json, examples/collection.json, examples/collectionless-item.json, examples/core-item.json, examples/extended-item.json, examples/extensions-collection/collection.json, examples/extensions-collection/proj-example/proj-example.json, examples/simple-item.json, item-spec/json-schema/bands.json, item-spec/json-schema/basics.json, item-spec/json-schema/common.json, item-spec/json-schema/data-values.json, item-spec/json-schema/datetime.json, item-spec/json-schema/instrument.json, item-spec/json-schema/item.json, item-spec/json-schema/licensing.json, item-spec/json-schema/provider.json, package.json
1. Update version numbers to v1.1.0
=> v1.1.0 release
