- implementations/raster-foundry/overview.md
- implementations/raster-foundry/spec.json
This pull request adds the Raster Foundry specification and description. I used the Planet description and specification as a template for this one.
I think I caught everything that was relevant and excluded things that were not (users, organizations, etc.). I erred a little bit on the side of keeping things in because some of the API endpoints are relevant to the additional functionality section. Happy to make edits though if you want less.
> Add Raster Foundry Specification and Description

- api-spec/spec.yaml
From chat on gitter with @joshfix and  @tomkralidis - in the rush to rename 'features' to 'items' we went a bit too far and failed to be an actual featurecollection.
Being a real GeoJSON featurecollection enables lots of software to easily visualize the results. So this rolls it back.
> changed spec from items to features

- json-spec/json-schema/stac-item.json
Changed assets to a object (dictionary)
added thumbnails as an optional item in assets, set the type to #asset
moved requirements from the root properties into the referenced core properties
> updated stac-item json schema for hackathon 2

- implementations.md
Seems that leaving the 'http://' prefix out assumes that the link is relative to the repo
> Fixing broken links

- api-spec/WFS3-core.yaml
I've spent some time this week working toward an updated OpenAPI spec for the union of WFS3 core, STAC core, and STAC extensions. Of course, the starting point has to be a usable WFS3 core yaml doc. Such a doc doesn't yet exist, and there are at least three sources of information:
- **Sample OpenAPI doc** (https://github.com/opengeospatial/WFS_FES/blob/master/openapi.yaml)
- **OpenAPI fragments** (https://github.com/opengeospatial/WFS_FES/tree/master/core/openapi)
- **Latest draft of the core standard** (https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html)
Unfortunately, these are not synchronized, resulting in contradictions. The wfs3-core.yaml doc is my attempt to reconcile these sources. In general, I have given deference to the standard doc, as it seems most up-to-date, …
> WFS3 core yaml doc

- json-spec/extensions/stac-collection-spec.md
a draft spec for a Collection extension. A Collection is simply a way to combine common metadata into a single record that applies to a group of `Item` records.
> add Collection extension spec

- extensions/examples/L1T-collection.json
- extensions/examples/landsat8-merged.json
- extensions/examples/landsat8-sample.json
- extensions/stac-eo-spec.md
- json-spec/examples/digitalglobe-sample.json
This removes the eo:crs field from the EO extension and replaces it with eo:epsg 
Examples are updated, but the JSON schemas have not been (and are outdated due to other recent changes as well).
> eo:crs to epsg

- json-spec/json-schema/stac-item.json
The JSON schema turned out to be mostly correct for the links, treating them as an object. Was just a syntax error with an extra trailing bracket.
Thanks to @abarciauskas-bgse for finding the error!
> remove trailing bracket

- extensions/stac-collection-spec.md
Several edits on the collection extension, to hopefully make things more clear.
I changed 'name' to not be required, since I feel like many metadata things that have two of (name, id, title) often get people just repeating them. So made 'id' the required one, with name the optional 'display name'. But please correct if I got it wrong.
And let me know if I got any of the other required/optional stuff wrong. 
Also added in some more color on the Collection JSON, since it's not really described / specified.
> adds more information about the various fields and how to use them

- json-spec/examples/CBERS_4_MUX_20170528_090_084_L2.json
- json-spec/examples/README.md
- static-catalog/examples.md
Some minor broken links also fixed.
CBERS static STAC catalog will be reset to use 0.5.0 for the next scene ingestions, starting 07/03.
Maybe not in time for 0.5.0, but this could be part of a 0.5.1 minor.
> Updating CBERS example description

- json-spec/json-schema/stac-item.json
- json-spec/json-spec.md
- static-catalog/README.md
- static-catalog/json-schema/catalog.json
[issue #139](https://github.com/radiantearth/stac-spec/issues/139) - specifically requests a required mime type to be added to assets.  This is what this PR does
[issue #138](https://github.com/radiantearth/stac-spec/issues/138) - Asks about a format field in the catalog.  I've removed this from the catalog as it doesn't make sense to repeat this information from the item assets
> add type to asset

- extensions/examples/L1T-collection.json
- extensions/examples/landsat8-merged.json
- extensions/stac-collection-spec.md
This PR changes the extensions examples to match the field descriptions in https://github.com/radiantearth/stac-spec/blob/master/extensions/stac-eo-spec.md
> Spell out FWHM to match eo:bands field descriptions

- extensions/stac-eo-spec.md
During STAC sprint 3 we discussed that it seems wrong that cloud cover can't be set to 0, i.e. no clouds.
@matthewhanson
> Allow 0 for cloud cover.

- extensions/scientific/README.md
- extensions/scientific/example-merraclim.json
- extensions/scientific/schema.json
Originally defined by the dataset group during the STAC sprint 3. Added in advance of the dataset spec as I think this can already be useful and tested before-hand for catalogs and later be adopted by/to the dataset spec.
Includes README, JSON schema and an example.
> Added scientific extension for STAC catalogs

- extensions/stac-eo-spec.md
To quote wikipedia "The micrometre (International spelling as used by the International Bureau of Weights and Measures) or micrometer (American spelling), also commonly known by the previous name micron..."
> wordsmith micron to standard term micrometres

- catalog-spec/README.md
Recommendations moved elsewhere, so removing this paragraph and its broken link.
> Removed recommendation section

- catalog-spec/catalog-spec.md
- collection-spec/collection-spec.md
1. The child rel type for catalogs should also allow to link to collections, otherwise collections in catalogs would not really work.
2. There are also other discrepancies for the root/parent/child rel types in the catalog and collection specs. Tried to fix them.
3. Removed requirement to have an absolute URL in as root in the catalog. We don't follow this in our examples anyway and it is not required in collections and items. Is that okay or should we aim for something different here?
Please review carefully. Thanks!
> Relation type consistency across specs

- extensions/commons/README.md
- extensions/commons/examples/landsat-collection.json
- extensions/eo/README.md
- extensions/eo/example-landsat8.json
Addresses #284 
I've removed eo:constellation from landsat examples since landsat-8 does not belong to a constellation if we follow the new definition proposal.
> eo:constellation proposal, examples updated

- item-spec/item-spec.md
In some cases, `Item`s may have descriptive titles. This documents a key that _may_ be used for such purposes.
Refs #310
> Document 'title' as a commonly-used property

- CHANGELOG.md
- api-spec/WFS3core+STAC.yaml
- api-spec/definitions/STAC-collections.fragment.yaml
- collection-spec/collection-spec.md
- collection-spec/examples/sentinel2.json
- collection-spec/json-schema/collection.json
- extensions/commons/examples/landsat-collection.json
- extensions/transaction/WFS3core+STAC+extensions.yaml
As discussed on Gitter and GitHub (#302).
We mostly agreed on type => role and the other changes are a proposal by me based on feedback from @mojodna that asks to allow specifying the licensor. And also, string was already flawed before, because a provider could be everything from the list of options.
> #302: Provider type to roles, string to array, added licensor, added descripion

- extensions/eo/README.md
As discussed on Gitter, null values are not allowed in the JSON schemas and therefore those fields should be omitted.
> Removed null valued fields from examples

- extensions/eo/schema.json
The spec explicitly allows setting eo:epsg to null, but the JSON schema would report the null value as invalid as only integer is set as data type. Fixing this.
Resolves #330.
> Allow null for eo:epsg in JSON schema

- CHANGELOG.md
* Added the `item` extension to the removal notice
* Removed "Providers Object in collections" as it won't make sense in a 0.6-stable release (was changed only between RCs)
* Formatting changes
> Fixes to the changelog

- extensions/eo/README.md
- extensions/eo/example-landsat8.json
* MInor formatting fixes for consistency
* Added null to the allowed types for eo:epsg
* Fixed example, which used "id" for bands instead of "name"
> Minor fixes for the EO extension.

- extensions/README.md
In the extension maturity model I added that a JSON schema is needed to get to 'pilot'.
Seems to me that if an idea is actually fleshed out then it should have the tool to let others validate properly.
> Added a requirement for a schema

- extensions/commons/README.md
Seems we missed that in the last release - there were examples for the commons extension, but the readme said there are no examples.
> Add example links to commons extension readme.

- item-spec/json-schema/geojson.json
Brings the geojson stac spec schema reference up to draft-06, to the same version of the other stac schemas. Used to minimize hangups with third-party software. Based off of a conversation in gitter with @cholmes 
The resulting JSON standard file was checked against https://www.jsonschemavalidator.net/ to ensure validity with json-spec draft-06.
> Ensure uniformity of jsonspec standards

- .circleci/config.yml
This PR changes the circle ci config to use the appropriate cli name
https://github.com/sparkgeo/stac-validator/pull/39
> Fix for the broken CI

- catalog-spec/json-schema/catalog.json
- collection-spec/json-schema/collection.json
Enforce the actual version number for stac_version. Otherwise you could add anything, but we actually want the specific version number in there. This also helps to enforce non-mixed catalogs, which is a requirement in the spec.
> Enforce the actual version number for stac_version.

- extensions/datacube/README.md
- extensions/datacube/example.json
- extensions/datacube/schema.json
I had some back and forth with myself in the last days how to best describe the vertical dimensions. The previous draft was not very strict in enforcing several aspects such as the axis only used for spatial dimensions. Now it is clearly defined and strictly checked in the JSON schema. In the meantime the other PR was already merged so we need another iteration, sorry for the inconvenience. Should have communicated that in the other PR.
> Data cube extension: Better JSON Schema and vertical dimensions better described

- extensions/sar/README.md
- extensions/sar/schema.json
I noticed that I named a field incorrectly when creating the SAR JSON Schema.
Edit: Added two improvements for field descriptions.
> SAR: Wrong field name used in JSON Schema + description fixes

- api-spec/STAC+extensions.yaml
- api-spec/extensions/fields/README.md
- api-spec/extensions/fields/fields.fragment.yaml
- api-spec/openapi/STAC.merge.yaml
I'm fixing two issues here, which I found when working on the other API PRs:
1. In one of the merge.yaml files, the path to the OpenAPI files was not correct: openapi-schema => openapi.
2. In the OpenAPI document it says, that exclude and include parameters are arrays. Throughout the examples comma-delimited strings were used instead. Changed to arrays. (Or we need to change the OpenAPI to comma-delimited, but that's not so easy, I guess.)
> Fixing two API issues (file paths, include/exclude data type)

- api-spec/STAC-extensions.yaml
- api-spec/STAC.yaml
- api-spec/openapi/STAC.yaml
- api-spec/openapi/WFS3.yaml
interim solution for https://github.com/geojson/schema/issues/7
use hosted copies of geojson schemas from here: https://github.com/radiantearth/stac-site/tree/master/assets
> update schema to point to hosted copy of geojson schema

- process.md
* Got rid of the swaggerhub spec
* Mentioned checking the online docs (likely to go away once we are sure this 'just works')
* Updated language a bit on RC's, since we decided on 0.7.0 not to do an RC since there weren't tons of changes (though we may live to regret that)
> Updates to dev process

- catalog-spec/catalog-best-practices.md
This is explained later in the document but in the way that is currently presented it looks like the name should always be `catalog.json` which is not the case.
> collection.json is also recommended for catalog filenames

- api-spec/examples.md
The API examples page primarily focused on dynamic queries against the `/collections/{collection_id}/items` endpoint, which is limited to only the `limit`, `time`, and `bbox` parameters.  Because of the limitations, we should be driving STAC users who wish to perform dynamic queries to the `/stac/search` endpoint.
In this PR, the examples have been reworked to show examples against the `/stac/search` endpoint.  A single example has been left to show how to query the collections endpoint and outline that the collections endpoints does not support HTTP POST.
> Rework API examples page

- api-spec/extensions/fields/README.md
The example requests for the fields api spec extension were incorrect.  Updated to align with the structure defined in the specification.
Signed-off-by: Josh Fix <josh@federal.planet.com>
> Fixed fields api extension example

- api-spec/api-spec.md
I added the original language, as there was no explicit statement about it.  In the API I maintain, we only allowed one or the other, as it was almost certainly an error if a client tried to submit both.  I think this should be the behavior of the STAC API.
> make clear api should only have one of bbox or intersects

- api-spec/api-spec.md
Related to WFS changes
https://github.com/opengeospatial/WFS_FES/pull/240
and 
https://github.com/opengeospatial/WFS_FES/issues/236
> remove /api endpoint from WFS 3 description, as it is no longer required

- api-spec/STAC-extensions.yaml
- api-spec/STAC.yaml
- api-spec/openapi/STAC.yaml
- extensions/label/examples/multidataset/catalog.json
- extensions/label/examples/multidataset/spacenet-buildings/catalog.json
- extensions/label/examples/multidataset/zanzibar/catalog.json
- extensions/label/examples/spacenet-roads/roads_item.json
Two fixes:
1. Fixed issues in the label extension examples 
- Invalid version numbers
- Commas after last element in array
2. Re-generated the STAC API files as they seem to be outdated (seems a PR missed to run `npm run generate-all`)
> Fixed label extension examples and re-generated OpenAPI files

- api-spec/STAC-extensions.yaml
- api-spec/STAC.yaml
- api-spec/extensions/STAC-extensions.fragment.yaml
- api-spec/extensions/STAC-extensions.merge.yaml
- api-spec/extensions/search/search.fragment.yaml
- api-spec/extensions/transaction/transaction.fragment.yaml
- api-spec/openapi/WFS3.yaml
Here's a YAML definition for the search extension as it was missing from STAC-extensions.yaml as of now.
In contrast to the JSON Schema, I did not make `search:metadata` required in the YAML. 
Also added the Transaction extension to the STAC-extensions.yaml.
Plus: Some fixes.
> search + transaction extension added to STAC-extensions.yaml

- extensions/pointcloud/README.md
- extensions/pointcloud/examples/example-autzen.json
There was a duplicate of the field `schema` in the fields of the point cloud extension.
I guessed that it should be required... cc @hobu @adamsteer
In addition, removed the Single Item extension properties from the example as the extension was removed.
> Removed duplicated field `schema` in the PC extension

- extensions/checksum/json-schema/schema.json
- extensions/datacube/json-schema/schema.json
- extensions/datetime-range/json-schema/schema.json
- extensions/eo/json-schema/schema.json
- extensions/sar/json-schema/schema.json
- extensions/scientific/json-schema/schema.json
Two changes:
* Absolute links changed to relative in JSON schemas (#528) 
* Removed "type: object" as it is not necessary due to "allOf".
> Absolute links changed to relative in JSON schemas (#528) and clean-up.

- CHANGELOG.md
- collection-spec/collection-spec.md
- item-spec/item-spec.md
**Related Issue(s):** #544
As discussed in the working session, trying to make providers and license not overly complicated and add `various` as license option.
> Make license and providers consistent between Collection and Item (#544)

- CHANGELOG.md
**Related Issue(s):** #545 
1. Update CHANGELOG with older commits that weren't yet in the CHANGELOG
> update CHANGELOG with older commits

- catalog-spec/catalog-spec.md
- catalog-spec/json-schema/catalog.json
- collection-spec/collection-spec.md
**Related Issue(s):** #542
1. Allow summaries to specify additional statistical values
> Allow summaries to specify Stats (#542)

- extensions/README.md
- extensions/eo/README.md
**Related PR(s):** #567 (closed because the branch based on master and a fairly old fork)
Addresses issue raised in STAC/Lobby 
> The README here https://github.com/radiantearth/stac-spec/tree/dev/extensions, under the section “Prefixes”, makes it seem like extension prefixes (like eo) are for keys in the properties object of the Item (this is also how https://github.com/radiantearth/stac-spec/blob/dev/extensions/eo/examples/example-landsat8.json is set up). The examples in https://github.com/radiantearth/stac-spec/blob/dev/extensions/eo/README.md make it seem like they go direclty into the body of the Item object. Is this a misplacement in the latter? Is extension Item information explicitly supposed to go into the properties object of the Item?
1. Modifies examples …
> EO Extension Readme Updates (Version 2)

- item-spec/itemcollection-spec.md
**Related Issue(s):**
None
Fix broken link to search extension in ItemCollection spec markdown document.
> Fix link to Search Extension in ItemCollection spec

- api-spec/extensions/search/README.md
1. Just removing the third *, which was meant to make things bold, but only two * are required.
> Fixing typo

- .gitignore
- CHANGELOG.md
- collection-spec/examples/landsat-item.json
- extensions/asset/examples/example-landsat8.json
- extensions/eo/README.md
- extensions/eo/examples/example-landsat8.json
- extensions/label/examples/multidataset/spacenet-buildings/AOI_2_Vegas_img2636.json
- extensions/label/examples/multidataset/spacenet-buildings/AOI_3_Paris_img1648.json
- extensions/label/examples/multidataset/spacenet-buildings/AOI_4_Shanghai_img3344.json
- extensions/label/examples/multidataset/zanzibar/znz001.json
- extensions/label/examples/multidataset/zanzibar/znz029.json
- extensions/label/examples/spacenet-roads/roads_source.json
- item-spec/examples/CBERS_4_MUX_20181029_177_106_L4.json
- item-spec/examples/landsat8-sample.json
- item-spec/item-spec.md
**Related Issue(s):** 
https://github.com/radiantearth/stac-spec/issues/535
1. Changed GeoTIFF type from `image/vnd.stac.geotiff` to `image/tiff; application=geotiff`
> Changed GeoTIFF type from `image/vnd.stac.geotiff` to `image/tiff; application=geotiff`

- CHANGELOG.md
- extensions/label/README.md
- extensions/label/examples/multidataset/spacenet-buildings/AOI_2_Vegas_img2636.json
- extensions/label/examples/multidataset/spacenet-buildings/AOI_3_Paris_img1648.json
- extensions/label/examples/multidataset/spacenet-buildings/AOI_4_Shanghai_img3344.json
- extensions/label/examples/multidataset/zanzibar/znz001.json
- extensions/label/examples/multidataset/zanzibar/znz029.json
- extensions/label/examples/spacenet-roads/roads_item.json
- extensions/label/schema.json
- extensions/pointcloud/README.md
- extensions/pointcloud/examples/example-autzen.json
- extensions/pointcloud/pdal-to-stac.py
**Related Issue(s):** #586
1. Pluralized field names in label extension (see #586)
2. Pluralized field name (schema => schemas) in point cloud extension
I hope I found all fields that should have plural forms.
> Pluralized forms of fields

- CHANGELOG.md
- extensions/single-file-stac/README.md
1. Found that there was a missing `[` in the collections data type.
2. Fixed the tables (for stricter Markdown readers).
> Single File STAC: Documentation fixes

- CHANGELOG.md
- extensions/eo/README.md
- extensions/label/examples/multidataset/spacenet-buildings/AOI_2_Vegas_img2636.json
- extensions/label/examples/multidataset/spacenet-buildings/AOI_3_Paris_img1648.json
- extensions/label/examples/multidataset/spacenet-buildings/AOI_4_Shanghai_img3344.json
- extensions/label/examples/multidataset/zanzibar/znz001.json
- extensions/label/examples/multidataset/zanzibar/znz029.json
- item-spec/examples/CBERS_4_MUX_20181029_177_106_L4.json
- item-spec/item-spec.md
**Related Issue(s):** #594, #535 
1. I think PR #594 was missing a deprecation notice containing the old media types.
2. Also, in the COG mailing list discussion it seemed that people were not super happy with a boolean flag, but rather would prefer it being a profile. Therefore proposing to changing from `cloud-optimized=true` to `profile=cloud-optimized`.
I think we should definitely merge point 1. Point 2 is open for discussions and I can revert that if nobody likes it.
> Media types once again

- extensions/label/README.md
Just found two typos introduced in #597.
> Fixed typo in label readme

- collection-spec/examples/sentinel2.json
- item-spec/examples/itemcollection-sample-full.json
- item-spec/examples/sample-full.json
- process.md
1. Item example: There was a thumbnail link in links, which should be in assets.
2. Item examples: Removed the non-standardized "product" fields.
3. Fixed typo "to to" in chapter Governance.
4. Removed discouraged use of license in collection summaries.
> Thumbnails are not meant to be in links

- CHANGELOG.md
- api-spec/extensions/search/schema.json
- extensions/asset/json-schema/schema.json
- extensions/checksum/json-schema/schema.json
- extensions/datacube/json-schema/schema.json
- extensions/datetime-range/json-schema/schema.json
- extensions/eo/json-schema/schema.json
- extensions/sar/json-schema/schema.json
- extensions/scientific/json-schema/schema.json
- extensions/single-file-stac/json-schema/schema.json
**Related Issue(s):** #618
1. Fixed JSON schemas for extensions: `$id` field matches file name.
> Fixed JSON schemas for extensions: `$id` field matches file name. #618

- CHANGELOG.md
- api-spec/STAC-extensions.yaml
- api-spec/STAC.yaml
- api-spec/api-spec.md
- api-spec/examples.md
- api-spec/extensions/fields/README.md
- api-spec/extensions/fields/fields.fragment.yaml
- api-spec/extensions/query/README.md
- api-spec/extensions/query/query.fragment.yaml
- api-spec/extensions/search/README.md
- api-spec/extensions/sort/README.md
- api-spec/extensions/sort/sort.fragment.yaml
- api-spec/openapi/STAC.yaml
- best-practices.md
- catalog-spec/README.md
- collection-spec/examples/landsat-item.json
- extensions/eo/examples/example-landsat8.json
- extensions/single-file-stac/examples/example-search.json
- item-spec/README.md
- item-spec/examples/itemcollection-sample-full.json
- item-spec/item-spec.md
- item-spec/itemcollection-spec.md
**Related Issue(s):** https://github.com/opengeospatial/ogcapi-features/issues/154
- The STAC API endpoint `/stac` has been merged with `/`
- The STAC API endpoint `/stac/search` is now called `/items`
> Renamed STAC endpoints

- CHANGELOG.md
- collection-spec/collection-spec.md
- collection-spec/examples/landsat-collection.json
- collection-spec/examples/sentinel2.json
- extensions/README.md
**Related Issue(s):** #660
1. Added extension best practice for arrays and objects
2. Based on that specified that summarized arrays are merged (#660)
> Arrays and Objects in Extensions /  How to summarize arrays (#660).

- collection-spec/collection-spec.md
1. Update Collection Temporal Extent interval field definition to be a string rather than a number.  The description and all our examples are RFC3336 strings, but the type was number. Also replaced the confusing term "timestamp" with "datetime" per RFC3336 term. 
> Collection: Fix type of interval array, should be string instead of number

- CHANGELOG.md
- api-spec/README.md
- api-spec/package-lock.json
- api-spec/package.json
**Related Issue(s):** None, it just annoyed me every single time I was working on the STAC API.
Make human-readable version of API easily accessible by:
1. Make the links to the rendered OpenAPI versions more prominent
2. Allow development versions to be rendered using redoc-cli and the following commands: `npm run serve` and `npm run serve-ext`.
I hope you'll love this simplification as much as I do!
> Make human-readable version of API easily accessible

- CHANGELOG.md
- api-spec/STAC-extensions.yaml
- api-spec/STAC.yaml
- api-spec/openapi/STAC.yaml
- collection-spec/examples/landsat-collection.json
- collection-spec/examples/sentinel2.json
- extensions/asset/examples/example-landsat8.json
- extensions/commons/README.md
- extensions/commons/examples/landsat-collection.json
- extensions/datacube/examples/example-collection.json
- extensions/eo/README.md
- extensions/eo/examples/example-landsat8.json
- extensions/eo/json-schema/schema.json
- extensions/projection/examples/example-landsat8.json
- extensions/single-file-stac/examples/example-search.json
Remove gsd and accuracy from eo:bands which are spatial attributes, not spectral attributes and thus do not fit in here. Perhaps they belong in the asset, but there is currently no known use case for including these values so they should be removed. 
1. remove gsd from eo:bands field in EO extension
2. remove `accuracy` field from `eo:bands` which appeared only in the readme and schema,is related to gsd
> Remove eogsd

- api-spec/STAC-extensions.yaml
- api-spec/STAC.yaml
- api-spec/openapi/STAC.yaml
- extensions/asset/README.md
- item-spec/item-spec.md
1. We forgot to allow Commonmark in the asset description. There's no good reason to not allow it when all other descriptions allow it.
2. We forgot to add the asset description field in the API.
> Align asset description

- extensions/asset/README.md
- item-spec/item-spec.md
**Related Issue(s):** #709
1. Add a data role
2. Add links
3. Change STRONGLY RECOMMENDED to a different place. It is a bit strange to strongly recomment thumbnail, but not data. Therefore I removed it from table and added a bit context to the recommendations. 
> Add data role

- implementations.md
1. Added Radiant MLHub to the list of API implementations
> Added Radiant MLHub to implementations

- CHANGELOG.md
- api-spec/STAC-extensions.yaml
- api-spec/extensions/transaction/transaction.fragment.yaml
none
1. Respond with as specific a response as possible when we know what went wrong with an item update in api transactions extension PUT. `BadRequest` and `NotFound` don't tell the user that they should refresh the object and try again, while a `PreconditionFailed` for a request with an `If-Match` header is extremely clear
> Respond with PreconditionFailed when If-Match header invalid

- collection-spec/json-schema/collection.json
- extensions/sat/json-schema/schema.json
- item-spec/examples/landsat8-sample.json
- item-spec/json-schema/item.json
N/A
1. Fix an old ref link to instrument extension in sat schema
2. Updates the list of stac_extensions in item and collection schemas to match current extensions directories
> Small schema corrections

- CHANGELOG.md
- api-spec/STAC-extensions.yaml
- api-spec/extensions/sort/README.md
- api-spec/extensions/sort/sort.fragment.yaml
https://github.com/radiantearth/stac-spec/issues/727
1. Changed sort api extension to use "+" and "-" field prefixes to define sort order for GET requests
> Sortby update

- CHANGELOG.md
- api-spec/STAC-extensions.yaml
- api-spec/STAC.yaml
- api-spec/extensions/sort/sort.fragment.yaml
- api-spec/extensions/version/version.fragment.yaml
- api-spec/openapi/STAC.yaml
**Related Issue(s):** Fixed #730 and #726, also related to #724
1. The STAC-extensions.yaml was broken as the Version extension referred to a non-existing schema. Fixed in commit https://github.com/radiantearth/stac-spec/commit/f9bf4b82107949005801e706b970dc2cccb3f72a.
2. License Expressions were removed in the last release, but were still mentioned in the API. Removed with commit https://github.com/radiantearth/stac-spec/commit/de3f49f2c122ac1b6b0f5394d8b262fd3a12ac2e
3. There was a white-space issue as discussed in PR #728. I figured out it is because some lines in the YAML files are longer than 80 chars and the YAML merge tool doesn't like that as it tries to wrap things at 80 lines. So I fixed it by fixing the line lengths. That looks a bit weird in diff, but …
> Fixes for the API

- extensions/sat/README.md
- extensions/scientific/README.md
- extensions/view/README.md
> Remove commons recommendation

- extensions/sar/README.md
1. Fixed description for sar:pixel_spacing_range
> Fixed description for sar:pixel_spacing_range

- .github/pull_request_template.md
**Related Issue(s):** #749
1. Removes the requirement to run the api script, since we moved the api stuff out.
> Remove api building requirement

- extensions/asset/examples/example-landsat8.json
1. Fixes the asset extension example. The link was part of the assets and not on the top level.
> Fix asset extension example

- .github/pull_request_template.md
**Related Issue(s):** #768
1. Added a reminder to the PR checklist to help remind people they should base their PR's against dev.
> Added reminder for basing PR's against dev

- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
**Related Issue(s):** #770, #775, #752
1. Added code of conduct #775
2. Updated PR template #770 #752
This needs to be on master to get reflected throughout the repo.
I discarded the CHANGELOG change from #775 as it's already using the new "markdown" style and had some conflicts. We can merge the CHANGELOG later for the next release, I think.
> Code of Conduct / PR template (for master)

- CHANGELOG.md
- extensions/projection/README.md
- extensions/projection/examples/example-landsat8.json
- extensions/projection/json-schema/schema.json
**Related Issue(s):** #756
1. Incorporate the proposed grid extension changes into the projections extension
2. Include two new properties, `proj:shape` and `proj:transform`
> Update proj extension to include grid

- README.md
- collection-spec/collection-spec.md
- item-spec/itemcollection-spec.md
**Related Issue(s):** #766 
1. Removed the 'warnings' from each of the specs.
2. Updated the readme to comment on 'beta' stability instead of a big 'warning'.
> Remove warnings about spec instability

- best-practices.md
- item-spec/examples/sentinel2-sample.json
- item-spec/item-spec.md
**Related Issue(s):** #789 
1. Moved section on common asset fields to best-practices
2. Moved example in item-spec.md to be in the s2 example
3. Cut the 60m assets from the s2 example, since they don't add much value imho and made the gsd stuff less clear. (Possibly controversial - the example is no longer aligns as closely with actual sentinel stac catalogs, but I think that's ok, as the examples in stac should be instructive imho. People can go
to the actual public catalogs to see the full example.
I don't believe this warrants a changelog entry, but happy to do one if others feel it should.
> Asset metadata cleanup

- CHANGELOG.md
- collection-spec/json-schema/collection.json
- extensions/item-assets/README.md
- extensions/item-assets/json-schema/schema.json
**Related Issue(s):** #799
1. Change the specific set of required fields to just require two fields. Idea originates in PR #754
2. Fix stac_extension entry for "item-assets", was forgotten to be renamed in #787
> Item Asset Definition: Don't specify the required fields

- CHANGELOG.md
- CONTRIBUTING.md
**Related Issue(s):** #773 and a bit of #793 
1. Reworked the contributing.md document to reflect maturity of spec
2. Added instructions on installing and running check-markdown locally
> Contributing.md improvements - instructions to run check-markdown locally

- best-practices.md
- item-spec/item-spec.md
**Related Issue(s):** #801 
1. Added a best practices section for use of `datetime`
2. 
> added best practice for datetime - #801

- collection-spec/examples/landsat-collection.json
1. Fix collection example. Those stac_extensions are only defined for items.
> Fix invalid STAC extensions in Collection example

- CHANGELOG.md
- catalog-spec/json-schema/catalog.json
- collection-spec/json-schema/collection.json
- extensions/checksum/README.md
- extensions/checksum/json-schema/schema.json
- extensions/collection-assets/json-schema/schema.json
- extensions/datacube/json-schema/schema.json
- extensions/eo/json-schema/schema.json
- extensions/item-assets/json-schema/schema.json
- extensions/label/json-schema/schema.json
- extensions/projection/json-schema/schema.json
- extensions/sar/json-schema/schema.json
- extensions/sat/json-schema/schema.json
- extensions/scientific/json-schema/schema.json
- extensions/single-file-stac/json-schema/schema.json
- extensions/tiled-assets/json-schema/schema.json
- extensions/timestamps/json-schema/schema.json
- extensions/version/json-schema/schema.json
- extensions/view/json-schema/schema.json
- item-spec/json-schema/item.json
**Related Issue(s):** #826, #816, #624 
1. Align label extension JSON Schema with rest of the extension schemas #624
2. Put stac_extension entries into extension schemas instead of core spec schemas #826 #816 
3. Make checksum extension schema also validate collections and catalogs.
4. Clarify in checksum extension that in can be used in collection assets, but can't be used in Item assets
5. Merge "Changed" sections in CHANGELOG
> Improve/Fix JSON Schemas

- collection-spec/json-schema/collection.json
- extensions/projection/json-schema/schema.json
- item-spec/json-schema/item.json
**Related Issue(s):** https://github.com/opengeospatial/ogcapi-features/issues/401
1. Allow 4 or 6 elements in bboxes, not 5.
> Don't allow 5 elements in bbox

- extensions/tiled-assets/README.md
- extensions/tiled-assets/json-schema/schema.json
**Related Issue(s):** #838 
1. Fixed typo
2. 
> fixed typo

- extensions/single-file-stac/README.md
#840 
1. Remove some old wording referencing commons extenson
- [n/a] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [n/a] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.
> remove reference to commons extension in single-file-stac

- CONTRIBUTING.md
1. Simple change to the CONTRIBUTING doc to add a note about passing schema files through jsonformatter for consistency.
> Updating contributing docs to use jsonformatter

- CHANGELOG.md
- extensions/pointcloud/README.md
- extensions/pointcloud/json-schema/schema.json
- package.json
Noticed there hadn't been any updates on this for a few months and thought I would give it a try (Sorry @adamsteer. If you already have something put together, I'm happy removing this PR.) I'm new to JSON schema so happy to get feedback.
One thing that I wasn't quite sure about was adding Property Dependencies on Statistics. So if a `stats` object is given, there should also be a `schema` object with the same name.
**Related Issue(s):** #391 
1. Adding schema file for pointcloud extension.
> adding JSON schema for pointcloud extension

- catalog-spec/catalog-spec.md
- collection-spec/collection-spec.md
- item-spec/README.md
- item-spec/common-metadata.md
- item-spec/item-spec.md
**Related Issue(s):** N/A
1. Fix some typos
2. Remove some references to the API spec, which are confusing without the API spec being in the same repo and https://github.com/radiantearth/stac-api-spec/issues/27 being added soon to the API.
> Minor fixes

- CHANGELOG.md
- collection-spec/collection-spec.md
**Related Issue(s):** N/A
1. As discussed on Gitter, allow multiple extents per collection
cc @davidraleigh 
> Multiple extents

- extensions/sar/examples/sentinel1.json
Just a fix for this SAR extension example, as `sar:bands` is no longer part of the spec.
> Fix SAR extension example

- item-spec/examples/sentinel2-sample.json
While technically valid JSON, having two "collection" keys generally means the first value is ignored, and is likely to cause confusion.
No related issue, figured a PR would be better than a issue
1. Removes a duplicate "collection" key from a example
SInce this was a minor change, I have not done the following:
> Remove duplicate "collection" from example

- extensions/projection/README.md
Quick fix to a link as it seems the documentation has moved.
> Fix PROJJSON link in projection extension README.

- extensions/README.md
- extensions/label/README.md
- extensions/sar/README.md
- extensions/sat/README.md
- extensions/tiled-assets/README.md
- principles.md
Fixes to spelling errors found with codespell version 1.16.0.
Pretty unexciting stuff.
1. Spelling corrections - No functional changes
> Spelling fixes for things found with codespell

- CHANGELOG.md
- extensions/item-assets/README.md
This PR adds language to the `item-assets` spec to clarify that collection-level asset objects should not contain properties that are not explicitly stated in the item's asset objects themselves.
This comes out of a discussion during STAC Sprint 6. It was determined that while allowing for asset properties to be defined in _only_ the collection-level asset objects was a way to save space, it would be more in line with the spec to have items explicitly contain all asset property information.
If you're currently using the item-assets extension to consolidate item-level asset object properties in an API setting, consider storing the STAC items without those consolidated properties internally as 'invalid' STAC items, and merge in the desired collection-level asset object properties at serving …
> Add clarification around collection-level assets in item-assets.

- item-spec/item-spec.md
Using tiled-assets instead of eo in example, eo currently scope is limited to Item
My editor removes spaces from lines' ends, I left this way. Reviewing is easier using the display rich diff.
**Related Issue(s):** no issue opened, discussed in gitter
> Fixing extension example

- extensions/eo/README.md
- item-spec/examples/sample-full.json
**Related Issue(s):** # n/a
1. Clarify text
2. Clarify which fields are for Item Asset and Item Properties
3. remove "QA" as an example for a band
4. expand the common_name rededge wavelength range to be what Sentinel-2 considers rededge
5. add Sentinel-2 rededge band #s
6. add NAIP bands as an example
> wordsmith text

- CHANGELOG.md
- extensions/label/json-schema/schema.json
**Related Issue(s):** #904 
1. Changes the label:classes property to not be required in the JSON schema
> Removed label:classes from required properties in label item

- CHANGELOG.md
- extensions/sat/README.md
- extensions/sat/examples/example-sentinel1.json
- extensions/sat/json-schema/schema.json
1. [Sat extension] Additional acquisition parameters
> [Sat Extension] Additional acquisition parameters

- CHANGELOG.md
- extensions/sar/json-schema/schema.json
1. The field `sar:polarizations` in assets was not validated correctly.
2. Also centralized the `sar:polarizations` definition (for re-use).
> JSON Schema for `sar:polarizations` in `assets` fixed

- CHANGELOG.md
- collection-spec/json-schema/collection.json
- item-spec/json-schema/provider.json
1. Fixed JSON Schema for `providers` (Collections and Items) to be an object and require a `name`
> Fixed JSON Schema for `providers`

- CHANGELOG.md
- extensions/scientific/README.md
- extensions/scientific/examples/collection.json
- extensions/scientific/examples/item.json
**Related Issue(s):** #915
1. Modify the scientific extension to state that the main DOI of the data should be linked with a reltype `cite-as`, removing the language that indicated that also the DOIs referenced in the `sci:publications` properties should have links with reltype 'cite-as'.
2. Modified the examples to reflect these changes.
> Only use "cite-as" link to refer to main publication for data.

- .github/CODEOWNERS
- README.md
- extensions/README.md
- extensions/collection-assets/README.md
- extensions/datacube/README.md
- extensions/eo/README.md
- extensions/file/README.md
- extensions/item-assets/README.md
- extensions/label/README.md
- extensions/pointcloud/README.md
- extensions/processing/README.md
- extensions/projection/README.md
- extensions/sar/README.md
- extensions/sat/README.md
- extensions/scientific/README.md
- extensions/single-file-stac/README.md
- extensions/tiled-assets/README.md
- extensions/timestamps/README.md
- extensions/version/README.md
- extensions/view/README.md
**Related Issue(s):** #928 
1. Add a [`CODEOWNERS`](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners) file
2. Add owners to each extension README
3. Document use of code owners in main README
> Add code owners

- best-practices.md
- catalog-spec/catalog-spec.md
- collection-spec/collection-spec.md
- item-spec/item-spec.md
**Related Issue(s):** #929 
1. Refactored 'rel' information to move the common IANA stuff to best practices, and tweaked the language of the sections so they just talk about the custom stac stuff. Note the decision to leave catalog more minimal in its language was deliberate, since there I didn't see how any of the official IANA ones applied, but I'm open to tweaking it with mroe.
> updated rel descriptions, moved info to best practice

- extensions/view/README.md
- extensions/view/json-schema/schema.json
Fixes #853
**Related Issue(s):** #853
As mentioned in #853, a negative view angle can be validly recorded in remove sensing data. Besides the example listed by the issue author, I've hit up against this in ASTER L1T data, in which the [product specification](https://lpdaac.usgs.gov/documents/300/ASTER_L1T_Product_Specification.pdf) states values will range from -90 to 90, and a many of the images record such a value in the HDF metadata.
This change modifies the spec text and JSON schema to allow for sun_elevation values ranging from -90 to 90.
> Modify valid range for sun_elevation to be -90-90.

- CHANGELOG.md
- best-practices.md
- catalog-spec/catalog-spec.md
- catalog-spec/json-schema/catalog.json
- collection-spec/collection-spec.md
- collection-spec/json-schema/collection.json
- item-spec/item-spec.md
- item-spec/json-schema/item.json
- item-spec/json-schema/provider.json
**Related Issue(s):** #952 , #957
1. Clean up the relative vs absolute link section to just link to the best practice.
2. Remove talk about static and dynamic catalogs, as those are now just in the best practice, not the spec itself.
> Relative vs absolute link edits

- CHANGELOG.md
- item-spec/item-spec.md
1. Added a 'role' for a visual asset. STAC Browser [looks for a visual 'key'](https://github.com/radiantearth/stac-browser/blob/eb078d4593482fa97c37a5f9123258645f50ecde/src/components/Item.vue#L289), and it seems cleaner to specific set it as a role. I'm not set on the name, and happy for tweaks on the description. Main idea is that for items with lots of assets that stac browser can default to one that will likely render the most easily.
> Add Visual role

- collection-spec/collection-spec.md
- extensions/README.md
- extensions/datacube/README.md
- extensions/eo/README.md
- extensions/label/README.md
- extensions/pointcloud/README.md
- extensions/projection/README.md
- extensions/sar/README.md
- extensions/sat/README.md
- extensions/tiled-assets/README.md
- extensions/timestamps/README.md
- extensions/view/README.md
- item-spec/common-metadata.md
1. Clarify which objects (e.g., Item Properties or Item Asset) fields apply to
2. Change uses of "Item Assets" to "Item Asset objects" so not to confuse with the item-assets extension (in general, I think we should adopt this style -- instead of pluralizing a STAC type (Type->Types), refer to `Type objects`)
> Item Properties and Item Asset clarification

- catalog-spec/json-schema/catalog.json
- collection-spec/json-schema/collection.json
**Related Issue(s):** #978
1. Move JSON Schema for summaries to Catalog, was forgotten in #942 
> Move JSON Schema for summaries to Catalog

- CHANGELOG.md
- extensions/projection/README.md
- extensions/projection/json-schema/schema.json
**Related Issue(s):** #909
1. `proj:geometry` allows all GeoJSON geometries instead of just a polygon.
> proj:geometry allows all GeoJSON geometries

- extensions/README.md
- extensions/file/README.md
1. In #999 and others we changed file extension to only apply for assets. Here are some additional changes that adopt this change (e.g. doesn't apply to Catalogs).
2. For Items it's clear where to place new fields, but it's not specified for Catalogs and Collections. Added what we currently do...
> Change file ext scope, clarify catalog & collection field placement

- CHANGELOG.md
- best-practices.md
**Related Issue(s):** #896 
1. Added best practice section with recommendations to put STAC json in public bucket even if data is in requester pays
2. recommendation to use cloud-specific request protocols
3. NOTE - did not yet add a link to the storage extension, since it's just a PR, and one that will get closed. Can add the recommendation in when we get a location for it.
> Requester Pays Best Practice

- best-practices.md
- examples/collection-only/collection.json
**Related Issue(s):** #1013 
1. Added a metadata collection asset to the collection-only example
2. added iso 19115 and 19139 to the 'roles' list in best practices.
> Collection assets example

- README.md
- catalog-spec/README.md
- item-spec/README.md
- overview.md
1. replace the use of "atomic unit" with a term less overloaded in computer science
> replace the use of 'atomic' with a less overloaded term

- examples/catalog.json
- examples/collection.json
1. fix two uses of RC.1 in examples
> fix uses of RC.1 instead of rc.1

- CHANGELOG.md
- collection-spec/collection-spec.md
- Collection Assets were specified as required (only in written text, not in JSON Schema), but that was incorrectly copied over from the former `collection-assets` extension. Collection Assets are not required.
(If this was meant to be required, then the JSON Schema needs a fix.)
> Don't require Collection Assets

- examples/simple-item.json
1. One of the item examples has the `collection` key inside properties, when I believe it should be at the top level.
> Fix Item example with collections inside properties

- extensions/projection/README.md
**Related Issue(s):** none
1. add a link to Centroid Objects in proj extension
- ~This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.~
> add centroid object link

- process.md
**Related Issue(s):** #1019 
1. Added 'core STAC team' from active STAC committers.
2. Overthrew our dictatorship, replaced with a democratic Project Steering Committee
3. Various minor updates to the process doc.
I'm considering no changelog needed, since it's not part of the spec / doesn't affect an implementor. But happy to put one in if desired.
> updated with info on PSC, core stac team, new process

- examples/collectionless-item.json
- examples/extended-item.json
- examples/extensions-collection/proj-example/proj-example.json
1. Update extension references to be URIs instead of shortnames
> updates stac_extensions values to replace short names with uris

- README.md
- catalog-spec/README.md
- catalog-spec/catalog-spec.md
- collection-spec/README.md
- item-spec/README.md
Clarify text around the uses of the different objects.   
Specifically, I think a new user coming to STAC would be confused about what the difference between a Catalog and Collection is, and how to divide their Items up. I also tried to be more precise in when we refer to a "STAC catalog" and the specific object type of Catalog -- this can get confusing, since you can have a small-c catalog that's a Collection. 
> docs: clarify description of Catalog, Collection, and Item

- CHANGELOG.md
- collection-spec/collection-spec.md
**Related Issue(s):** #1067 #1045
1. Clarify data types for values in summaries
> Clarify data types for summary values #1067 #1045

- CHANGELOG.md
- catalog-spec/json-schema/catalog-core.json
- item-spec/item-spec.md
- item-spec/json-schema/item.json
- item-spec/json-schema/provider.json
**Related Issue(s):** #1048
1. Add minLength requirement to required strings as discussed in #1048
> Add minLength requirement to required strings (core only) #1048

- examples/extensions-collection/proj-example/proj-example.json
- item-spec/item-spec.md
- item-spec/json-schema/item.json
- package.json
**Related Issue(s):** #1088
1. Node Validator was not updated yet to v1.x.x and thus was not able to correctly validate
2. Fix issues in examples that were found
3. Implement and clarify #1088
> Update STAC Node Validator, fix examples, fix #1088

- CHANGELOG.md
- collection-spec/collection-spec.md
**Related Issue(s):** 
- https://github.com/radiantearth/stac-spec/issues/1064
- https://github.com/opengeospatial/ogcapi-features/pull/520
1. Adopt clarification by OGC API - Features on multiple extents in collections
cc @cportele
> Clarification on multiple bounding boxes in an extent

- CHANGELOG.md
- catalog-spec/catalog-spec.md
- collection-spec/collection-spec.md
- item-spec/item-spec.md
**Related Issue(s):** #1077
1. For context see #1077, but it basically makes it more consistent that stac_extensions also allow to list extensions that are used in collection summaries.
2. Re-phrased the stac_extensions description in all specs.
3. Removed the wording around "multiple affected parts" as that should be clear from each individual stac_extensions description, which requires to list stac_extensions if they are implemented. That was mostly for the commons extension back in the days, but nowadays had no real good example anymore. The data cube example in collections for example was not really correct.
> Clarified stac_extensions

- examples/collection-only/collection.json
**Related Issue(s):** #1045 #1093 
1. Remove scientific so we can merge this, as discussed in https://github.com/radiantearth/stac-spec/pull/1093/files#r620248117 so we don't have to wait for https://github.com/stac-extensions/scientific/pull/2 to merge.
> remove scientific extension

- CHANGELOG.md
- best-practices.md
**Related Issue(s):** #1096 https://github.com/stac-utils/stactools/issues/87 https://github.com/stac-utils/stactools/pull/88 
1. Clarify in best practices that gsd used in assets should just be about the sensor, not the processing.
> Gsd clarifications for use in assets

- CHANGELOG.md
- catalog-spec/catalog-spec.md
- catalog-spec/json-schema/catalog-core.json
- collection-spec/collection-spec.md
- examples/catalog.json
- examples/collection-only/collection-with-schemas.json
- examples/collection-only/collection.json
- examples/collection.json
- package.json
**Related Issue(s):** #1045
1. Support JSON Schema in summaries - I hadn't had a lot of time to flesh out the language, improvements appreciated.
2. Rename Stats Object to Range Object
3. Fix collection examples (add missing stac_extensions entries), but that fails right now due to https://github.com/stac-extensions/scientific/pull/2
> JSON Schema in summaries #1045

- CHANGELOG.md
- overview.md
1. Added a 'foundations' section to the overview, to talk about the various standards we rely on.
2. Clarified that 'null' is not the same as leaving a field out.
> new overview section

- examples/collection.json
1. add missing projection declaration in `stac_extensions` in collection example
> add missing projection declaration in collection example

- CHANGELOG.md
- catalog-spec/json-schema/catalog-core.json
- collection-spec/json-schema/collection.json
- item-spec/json-schema/item.json
1. JSON Schemas don't allow "shortcuts" for core extensions any longer
> JSON Schemas don't allow "shortcuts" for core extensions any longer

- CHANGELOG.md
- collection-spec/collection-spec.md
**Related Issue(s):** #1125
1. An open date range to both sides is now allowed in the Collection's temporal extents.
> Collection: Open intervals for temporal extents

- CHANGELOG.md
- best-practices.md
**Related Issue(s):** https://github.com/radiantearth/stac-api-spec/issues/141
1. Due to the potential changes in the ItemCollections (see https://github.com/radiantearth/stac-api-spec/issues/141) and also due to the fact that it's not really part of the core spec, removed the ItemCollection from the Stac "detection" heuristic.
> Removed ItemCollection from STAC detection heuristic

- README.md
1. Removed stability note, moving key info to versions and about
> removed stability note and moved key info for 1.0.0

- examples/collection.json
N/A
`proj:epsg` should be summarised as an array of all values, not a Range Object, per [stac-fields](https://github.com/stac-utils/stac-fields/blob/v1.0.0-beta.10/fields.json#L575) and [other examples](https://github.com/radiantearth/stac-spec/blob/master/examples/collection-only/collection.json#L90).
> fix(examples): change epsg summary example to an array of all values

- CITATION.cff
Dang it, there was a `-` too much in the Citation YAML, which leads to incorrect rendering.
This PR should fix it that instead of 
`STAC Contributors, & . (2021). SpatioTemporal Asset Catalog (STAC) specification (Version 1.0.0). https://stacspec.org`
it renders as 
`STAC Contributors (2021). SpatioTemporal Asset Catalog (STAC) specification (Version 1.0.0). https://stacspec.org`
> Fix minor citation issue

- extensions/README.md
**Related Issue(s):** #1203
1. Remove the list of STAC extensions, only refer to stac-extensions.github.io for easier maintenance and updates
2. A lot of changes and improvements in wording/text, cater for recent changes e.g. in how we handle and write STAC extensions (scope list)
3. Better explain that you can basically extend every object
4. Tried to remove a bit of duplication
5. Moved extension maturity a level up as it is important for most chapters, not only for extending STAC
> Update extensions readme

- item-spec/common-metadata.md
Clarifies a text around timestamps a bit and aligns it to what the timestamp extension says.
> Clarify the text around timestamps a bit.

- CHANGELOG.md
- catalog-spec/json-schema/catalog.json
- collection-spec/json-schema/collection.json
- item-spec/common-metadata.md
- item-spec/json-schema/basics.json
- item-spec/json-schema/common.json
- item-spec/json-schema/datetime.json
- item-spec/json-schema/item.json
**Related Issue(s):** #1199 #1187
1. Validate common metadata also in Catalogs, Collections and Links. Also, re-uses the schemas from common metadata in Collections so that they don't diverge (which was the case).
2. Includes a very minor somewhat breaking change: Provider, Asset and Item descriptions can't be empty now. Either they need to be omitted or contain at least one character. This aligns with Catalog and Collection description as part of the common metadata model. 
> Better integrate common metadata

- CHANGELOG.md
- collection-spec/json-schema/collection.json
- examples/collection.json
- examples/extended-item.json
- item-spec/common-metadata.md
- item-spec/json-schema/basics.json
**Related Issue(s):** #1187
1. Keywords fields in common metadata to have it available in Stac Item 
> Keywords in common metadata

- CHANGELOG.md
- collection-spec/collection-spec.md
- collection-spec/json-schema/collection.json
**Related Issue(s):** #1243 
Two spatial bounding boxes in a Collection don't make sense and will be reported as invalid by the schema. ([#1243]
> Disallow two spatial bounding boxes in Collections

- CHANGELOG.md
- collection-spec/collection-spec.md
- examples/collection-only/collection-with-schemas.json
- examples/collection-only/collection.json
- examples/collectionless-item.json
- examples/extensions-collection/collection.json
- item-spec/common-metadata.md
**Related Issue(s):** #1232 
- The `license` field additionally supports SPDX expressions and the value `other`.
- The values `proprietary` and `various` are deprecated in favor of SPDX expressions and `other`.
>  Update license to follow OGC API - Records

- CHANGELOG.md
- item-spec/common-metadata.md
- item-spec/json-schema/basics.json
**Related Issue(s):** #1267
1. Add roles to common metadata, currently used in Assets, Providers, Contacts extension, and planned to be used in the CEOS ARD and Web Map Links extension for links.
> Add roles to common metadata #1267

- CHANGELOG.md
- item-spec/common-metadata.md
**Related Issue(s):** #1255
1. Clarify in descriptions that start_datetime and end_datetime are inclusive bounds
and I have opened issue/PR https://github.com/radiantearth/stac-api-spec/issues/444to track the change.
> Inclusive date time range

- CHANGELOG.md
- best-practices.md
**Related Issue(s):** #1168
1.  Link titles should exactly reflect the title of the corresponding entity
> Best practice: Align link titles

- CHANGELOG.md
- best-practices.md
- item-spec/item-spec.md
**Related Issue(s):** #1160
1. Disallow GeometryCollection in Item Spec (as defined in the schema) #1160
2. Reformatted the Item Field table to be more lightweight by moving geometry, bbox, and collection descriptions to separate sections. Also, clarified that RFC section 3.1 and 3.2 apply, for Geometry Object and null respectively.
> Disallow GeometryCollection, reformatting

- collection-spec/README.md
- collection-spec/collection-spec.md
- item-spec/README.md
- item-spec/item-spec.md
**Related Issue(s):** #1251
1. ItemCollection
2. CollectionCollection
> Describe ItemCollection and CollectionCollection

- best-practices.md
1. In the bands migration JSON example, there was an invalid trailing comma.
> Remove invalid trailing comma from docs
